- hosts: all
  become: yes
  tasks:

    - name: install gitlab-ce dependencies
      apt:
        name: ['ufw']
        state: latest
        update_cache: yes
        cache_valid_time: 3600

    - name: install ufw e configure
      ufw:
        rule: allow
        name: OpenSSH

    - name: enable ufw
      ufw:
        state: enabled

    - name: install Docker  
      apt:
        name: docker.io
        state: present
        update_cache: true

    - name: add $user to docker group
      user:
        name: pi
        group: docker

        #    - name: install apt fail2ban packages
        # apt: 
        # name: ['fail2ban', 'sendmail']   
        #state: latest
        #update_cache: yes
        #cache_valid_time: 3600

    - name: override the basic fail2ban configuration with .local file
      copy:
        src: jail.local
        dest: /etc/fail2ban/jail.local
        owner: root
        group: root
        mode: '0644'

    - name: install docker-compose
      apt:
        name: docker-compose

    - name: symbolic link
      file:
        src: /usr/bin/docker-compose
        dest: /usr/local/bin/docker-compose
        state: link
